# Generated by Django 4.0.4 on 2022-06-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_comment_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='issue_comment', to='projects.project'),
        ),
    ]
