# Generated by Django 4.0.4 on 2022-06-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_comment_issue_id_alter_comment_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_issue', to='projects.project'),
        ),
    ]
